### ISSUE TITLE
Why is there a locker?

### ISSUE THREAD

**Issue by peternavr** [digota/digota#12]
Why is there a locker/unlocker. I've noticed it's used in retrieving products. What problem is it trying to solve?

**Comment by yaronsumel** [comment]
So the basic concept behind the locker in distributed system is to sync access to objects across different nodes..  For instance:  client is deleting object while other client is retrieving it. Currently lock is part for most of the single object logic, list method has no lock logic.
```
Client #1 DelSomething -> TryLock -> [lock accuired] ->  Delete -> ReleaseLock -> Return Something 
                                                                                 \ 
Client #2 GetSomething -> TryLock -> --------- [wait for lock] -------------------*-----> Already deleted
```

**Comment by yaronsumel** [comment]
@clanstyles Closed.. feel free to comment if something isn't clear
