### ISSUE TITLE
Support Docker deploy or not.

### ISSUE THREAD

**Issue by billgo** [digota/digota#20]
Can support docker-compose deploy or not ?

**Comment by yaronsumel** [comment]
Yes, soon.

**Comment by billgo** [comment]
thanks man .

**Comment by roboto-cloud** [comment]
@yaronsumel some preview docker-compose.yml?

**Comment by yaronsumel** [comment]
@roboto-cloud @billgo sorry for the long waiting. here you go 
https://github.com/digota/digota/tree/master/docker
https://hub.docker.com/r/digota/digota/
