### ISSUE TITLE
Feature: Add Consul

### ISSUE THREAD

**Issue by billgo** [digota/digota#22]
Zookeeper need install java and JDK, 
I think  Consul is better.

**Comment by yaronsumel** [comment]
Good idea, everything is pretty much interface so it should be pretty easy to implement that.
If you want to implement it take a look at 
locker interface: https://github.com/digota/digota/blob/master/locker/locker.go
zookeeper handler: https://github.com/digota/digota/blob/master/locker/handlers/zookeeper/zookeeper.go

**Comment by billgo** [comment]
thanks man, 
I will try it .

**Comment by yaronsumel** [comment]
@billgo will arrive soon
