### ISSUE TITLE
Bug: multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by jshbrntt** [digota/digota#23]
Getting these errors when trying to install.

```shell
$ go get -u github.com/digota/digota
# github.com/digota/digota/storage/handlers/mongo
src/github.com/digota/digota/storage/handlers/mongo/mongo.go:182: multiple-value uuid.NewV4() in single-value context
# github.com/digota/digota/payment/service/providers/internalTestOnly
src/github.com/digota/digota/payment/service/providers/internalTestOnly/internalTestOnly.go:52: multiple-value uuid.NewV4() in single-value context
src/github.com/digota/digota/payment/service/providers/internalTestOnly/internalTestOnly.go:69: multiple-value uuid.NewV4() in single-value context
```

Here's a `Dockerfile` that reproduces this error.

```dockerfile
FROM golang:1.9
RUN go get -u github.com/digota/digota
ENTRYPOINT [ "digota" ]
```

**Comment by b4rti** [comment]
Same here on Docker alpine:latest and Desktop archlinux:testing

**Comment by b4rti** [comment]
uuid.NewV4() now returns (UUID, error) --> https://github.com/satori/go.uuid/commit/0ef6afb2f6cdd6cdaeee3885a95099c63f18fc8c 

fix --> https://github.com/digota/digota/pull/24

**Comment by yaronsumel** [comment]
Hey @synthecypher @b4rti sorry for the delay. i've updated master to have `vendor` in place to prevent such cases in the future.. please retry with the following `Dockerfile`.  Will start uploading builds into docker hub really soon :)

```yaml
FROM golang:1.11

RUN go get github.com/digota/digota

CMD [ "digota" ]
```
