### ISSUE TITLE
In-memory lock

### ISSUE THREAD

**Issue by thetooth** [digota/digota#8]
Implementing a simple in-memory locker would allow testing without dependencies as well as allow users to evaluate digota without much upfront effort.

**Comment by yaronsumel** [comment]
Sounds good.. 
What do to think about in-memory storage implementation for same reasons ?

**Comment by thetooth** [comment]
Might be a bit pointless given how easy it is to setup mongodb, a mock interface would be handy in end to end tests, but it's those kind of tests focus on finding edge cases in the happy path, not if a given component is failing.

**Comment by Gerifield** [comment]
It'll loose data easily. A simple file based could be a better storage option. (Or redis. ;) )

**Comment by yaronsumel** [comment]
PR #11

**Comment by yaronsumel** [comment]
Merged.. it is default now
